# Generated by Django 3.1 on 2026-01-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20260106_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='order_number',
        ),
    ]
